name: ecotrack
description: EcoTrack - app per stimare l'impatto ambientale degli acquisti
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mobile_scanner: ^3.5.5

  #http: ^0.13.6

  # UI
  cupertino_icons: ^1.0.2
  fl_chart: ^1.1.1   # opzionale, per grafici

  # ML + camera + barcode
  #google_ml_kit: ^0.20.0
  camera: ^0.11.2
  #flutter_barcode_scanner: ^2.0.0

  #google_mlkit_text_recognition: ^0.13.0
  #google_mlkit_barcode_scanning: ^0.13.0

  image_picker: ^1.0.7
  

  # Storage e utilità
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2

  # HTTP backend
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.3.3

flutter:
  assets:
    - assets\data\products_mock.json
    - assets\data\co2_per_category.json
  uses-material-design: true